server {
    listen 80;
    server_name febru.djncloud.my.id;

    root /var/www/html/public;
    index index.php index.html;

    error_log /var/log/nginx/lumen.error.log;
    access_log /var/log/nginx/lumen.access.log;

    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass project:9000;
        fastcgi_index index.php;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        fastcgi_param HTTP_HOST $host;
        fastcgi_param SERVER_NAME $host;

        fastcgi_param HTTPS on;
        fastcgi_param SERVER_PORT 443;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
        fastcgi_param HTTP_X_FORWARDED_SSL on;
        fastcgi_param HTTP_X_FORWARDED_HOST $host;
        fastcgi_param HTTP_X_FORWARDED_PORT 443;

        fastcgi_pass_request_headers on;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}